### PR TITLE
handle_push: fix problems with '/' in branch name

### LINKED ISSUE #16: Does not handle '/' in branch name

### PR DESCRIPTION
**Pull request by Nhqml**
Fix #16

### CODE REVIEW

File: src/bot/github.rs [hunk 1]
```diff
@@ -383,7 +383,7 @@ fn handle_push(event: PushEvent) -> Option<Response> {
 
     let branch = event
         .r#ref
-        .rsplit_once('/')
+        .split_once("refs/heads/")
```
Comment (alarsyo) [inline src/bot/github.rs:386]: `strip_prefix` would be better here

**Review by alarsyo — CHANGES_REQUESTED** [review]

**Review by alarsyo — APPROVED** [review]
