### PR TITLE
Misc fixes/improvements

### LINKED ISSUE #21: Add link to user profile when displaying username
It could be nice to add a link to user profile when a username is displayed

### PR DESCRIPTION
**Pull request by Nhqml**
Fix #21, at least party. I chose not to add the user link for **every** event (otherwise we would end-up with too many links in a single message) but only for event where there could be "unknown" users.

### CODE REVIEW

File: src/bot/github.rs [hunk 1]
```diff
@@ -183,16 +188,16 @@ fn handle_issues(event: IssuesEvent) -> Option<Response> {
...
-                write!(message, " body").unwrap();
+            if changes.title.is_some() && changes.body.is_some() {
+                write!(message, " title and body of issue ").unwrap();
+            } else if changes.title.is_some() {
+                write!(message, " title of issue ").unwrap();
+            } else if changes.body.is_some() {
+                write!(message, " body of issue ").unwrap();
+            } else {
+                error!("issue was edited but received an empty change!");
+                return None;
```
Comment (alarsyo) [inline src/bot/github.rs:199]: I think that deserves a `match`:

```rust
let changed = match (changes.title, changes.body) {
    (Some(_), Some(_)) => "title and body",
    (Some(_), None) => "title",
    (None, Some(_)) => "body",
    (None, None) => {
        error!("issue was edited but received an empty change!");
        return None;
    },
};
write!(message, " {} of issue ", changed).unwrap();
```

**Review by alarsyo — CHANGES_REQUESTED** [review]

**Review by alarsyo — APPROVED** [review]
